### ISSUE TITLE
Support for git diff syntax highlighting in dark color scheme

### ISSUE THREAD

**Issue by anshulguleria** [itsthatguy/theme-itg-flat#42]

**Comment by venetianthief** [comment]
GitGutter is supported in dark color scheme.

![2015-03-27 05_33_54-c__dev_github_chocolatey-io js_io js nuspec chocolatey-io js - sublime text](https://cloud.githubusercontent.com/assets/4130427/6865310/eac3b0a8-d442-11e4-8d3e-a3af51e7cf2f.png)

**Comment by anshulguleria** [comment]
But for *.diff files dosen't show up in colored syntax. I was using SublimeGit plugin and diff command shows syntax highlighting in monokai theme but not in this one.
![Image from subilmegit plugin](https://sublimegit.net/static/img/screenshots/screenshot-10.png)

This is how it shows up in monokai theme. (image take from [sublime git plugin site](https://sublimegit.net/)

**Comment by venetianthief** [comment]
ahh sorry read the title wrong and missed the 'syntax highlighting'.

**Comment by itsthatguy** [comment]
@anshulguleria do you know what it would take to integrate this?

**Comment by anshulguleria** [comment]
@itsthatguy No. Sorry but I don't know about integrating sublime plugins. Haven't worked on them :(

**Comment by jrappen** [comment]
@itsthatguy compare scopes from https://github.com/sublimehq/Packages/tree/master/Diff
