### ISSUE TITLE
Black Background in Find Textfields

### ISSUE THREAD

**Issue by mortik** [itsthatguy/theme-itg-flat#46]
Strange Black Background in find Textfields and Quick Find Bars.

![screenshot 2015-02-20 23 02 09](https://cloud.githubusercontent.com/assets/517703/6310187/9db6696c-b954-11e4-89a3-9de8ff906299.png)
![screenshot 2015-02-20 23 03 50](https://cloud.githubusercontent.com/assets/517703/6310205/c5e64a06-b954-11e4-85ea-951ff6f98f22.png)

Sublime Text 3 - Build 3065

**Comment by venetianthief** [comment]
Build 3083 is now out. See if that fixes your issue. If not are you running any additional plugins that could be interfering with the theme?

**Comment by mortik** [comment]
Sorry It seems to be a bug in RubyTest. For me is this issue resolved.
