### ISSUE TITLE
It's broken now...

### ISSUE THREAD

**Issue by vespakoen** [itsthatguy/theme-itg-flat#58]
Hey!

I have been happily using your theme for a long time, unfortunately the last update just broke it.
Hope you'll fix it =)

**Comment by Elfshame** [comment]
Can confirm. The theme is currently broken. Hoping for a quick fix!
Grateful for itg.flat. It's my only theme.

**Comment by LastRose** [comment]
Broken here too

**Comment by manuel-huez** [comment]
+1

**Comment by LastRose** [comment]
From what I can see a whole bunch of color values got removed ex. line 280
 -    "layer0.tint": [255, 255, 255, 200],
+    "layer0.tint": ,

**Comment by itsthatguy** [comment]
@LastRose can you please submit a link?

**Comment by LastRose** [comment]
Here is the history for the latest commit to the dark theme that you made
https://github.com/itsthatguy/theme-itg-flat/commit/0ff4b2e198ed44bf24b0c22b2273fb62716f32f2

**Comment by itsthatguy** [comment]
Ok, I'm working on a fix now. thanks for the heads up

**Comment by jaimeeee** [comment]
![screen shot 2015-04-17 at 14 40 16](https://cloud.githubusercontent.com/assets/258357/7210028/d5186ffa-e513-11e4-834a-65504f7acdaa.png)

Just in case someone is wondering.

**Comment by itsthatguy** [comment]
I've reverted back to a working version.

I'm about to update master with a version that I have working locally

**Comment by KaduAmaral** [comment]
It's broken... 

![broken](https://cloud.githubusercontent.com/assets/4316607/7210063/fa29f7f8-e524-11e4-95c6-6486da7639ad.png)

**Comment by itsthatguy** [comment]
If you remove the package and reinstall, it should be working now. (tested and verified)

**Comment by manuel-huez** [comment]
Is this me, or is the theme also not available on package control anymore? It simply doesn't show up anymore.

![screen shot 2015-04-17 at 13 15 31](https://cloud.githubusercontent.com/assets/1593272/7210125/e1f0e3f2-e503-11e4-81de-e8a9b6f99048.png)

**Comment by jaimeeee** [comment]
@manuel-huez you have to remove it first, then search for it.

**Comment by itsthatguy** [comment]
@manuel-huez if you try to install it, while it's already installed, it wont show up

**Comment by manuel-huez** [comment]
It is not installed anymore.

**Comment by itsthatguy** [comment]
@manuel-huez make sure that it's not an ignored package in your user preferences

**Comment by manuel-huez** [comment]
Well, the package just suddenly chose to show up again. There is no apparent problem with the theme for me anymore, other than the primary color being blue

**Comment by KaduAmaral** [comment]
Yeah, now is blue, the default beautiful color is gone... :/

**Comment by itsthatguy** [comment]
@KaduAmaral https://github.com/itsthatguy/theme-itg-flat/issues/60

**Comment by vespakoen** [comment]
Working again! Thanks for the effort.
For me, opening sublime and waiting a bit for it to check for updates, it automatically installed the new version (no need for removing first).

I consider it fixed!

**Comment by itsthatguy** [comment]
Thanks for the update!

**Comment by EvilRyuu** [comment]
http://i.gyazo.com/608b3e02333c2c3ec9028b034bdd6385.png

not working for me

**Comment by itsthatguy** [comment]
Reinstall it, and restart sublime

**Comment by itsthatguy** [comment]
Ah wait, yes. Light is not hooked up. I will get it set up tonight.

**Comment by itsthatguy** [comment]
Could you create a separate issue for the light theme not working?
