### ISSUE TITLE
itg.flat.light version still need a fix

### ISSUE THREAD

**Issue by EvilRyuu** [itsthatguy/theme-itg-flat#62]
![](http://i.gyazo.com/8af72cc4412714ce7fd3b648fb0b8912.png)

**Comment by itsthatguy** [comment]
This should be resolved here: https://github.com/itsthatguy/theme-itg-flat/commit/a9580fd566d7e3051c883986df330b729b56b32b

**Comment by itsthatguy** [comment]
Closing, assuming no longer an issue
