### ISSUE TITLE
Tabs being previewed do not display in italics

### ISSUE THREAD

**Issue by kirb** [itsthatguy/theme-itg-flat#69]
Usually, clicking once on a file from the sidebar makes it display in a preview mode, where clicking another file in the sidebar opens it in the same tab (closing the previous file) rather than a new tab. Typing into the file changes it to a normal tab again. The tab name is meant to be in italics; however it looks like this theme suppresses that. Comparison:

itg-flat:

![screen shot 2015-06-14 at 1 58 58 pm](https://cloud.githubusercontent.com/assets/773309/8147094/a792ccc6-129d-11e5-97cb-f0ff1f33b7f5.png)

Other themes:

![screen shot 2015-06-14 at 1 59 28 pm](https://cloud.githubusercontent.com/assets/773309/8147096/ab88cf6a-129d-11e5-8a11-67187c168055.png)

Running Sublime build 3083.

**Comment by itsthatguy** [comment]
This is currently in development, once the tests are passing it will be merged into master: https://github.com/itsthatguy/theme-itg-flat/pull/68

**Comment by itsthatguy** [comment]
https://github.com/itsthatguy/theme-itg-flat/pull/70

**Comment by itsthatguy** [comment]
Done

**Comment by kirb** [comment]
Wish I thought to check pull requests and not just issues before I filed this. Thanks!
