### ISSUE TITLE
Alignment of tabs to tree is slightly off

### ISSUE THREAD

**Issue by geckoseo** [itsthatguy/theme-itg-flat#71]
I love this theme, there is just one little niggle I have, so this is an enhancement request.

No matter what combination of tab height, tree size I use, there is a slight (or big) misalignment of the tabs row against the open folder tree. It would be prettier if they could match perfectly.

![1](https://cloud.githubusercontent.com/assets/2017303/8179747/9b126aa0-1410-11e5-8a03-9e00c153b173.png)

**Comment by itsthatguy** [comment]
Unfortunately this is going to be a problem for some size, thus the reason for ignoring it.

with medium sidebar:

![image](https://cloud.githubusercontent.com/assets/1118006/8191445/111bacf0-1436-11e5-8141-2e44dfa952a2.png)

**Comment by geckoseo** [comment]
thanks for clarifying
