### ISSUE TITLE
How to Apply just the Tab Styles

### ISSUE THREAD

**Issue by jhprks** [itsthatguy/theme-itg-flat#74]
How would I be able to just apply the tab styles from itg-flat and use a different color scheme (tomorrow night)?

**Comment by jhprks** [comment]
Okay, itg-flat is just a theme, just noticed that I can choose whether or not to use the color scheme.

**Comment by itsthatguy** [comment]
:+1:

**Comment by Weishi93** [comment]
Yeah this is only for the color scheme, but I'm still curious about your sublime style, not just about tab style, but also for the overall flat design style. How do you make it?

**Comment by Weishi93** [comment]
Oh I just reinstalled this theme and it's working now. Thank you for sharing this amazing theme
