### ISSUE TITLE
Issue when overriding the theme

### ISSUE THREAD

**Issue by EmmanuelBeziat** [itsthatguy/theme-itg-flat#77]
Hi !

I want to have a set of icon files ( https://github.com/mrmartineau/SetiUI-Icons-Sublime this one ), overriding itg.flat.dark. Like I usually do, I just put a new folder called like the theme, put the overriding files in it, create an empty theme file, and *voilà*. But this time, i'm having a strange issue.

** Step 1 ** ST is opened, before the folder where i've put the icons is correctly named :

![](http://image.noelshack.com/fichiers/2015/41/1444159183-step1.jpg)

** Step 2 ** Then I rename correctly the folder, and the icons are (almost) correctly set in ST :

![](http://image.noelshack.com/fichiers/2015/41/1444159184-step2.jpg)

** Step 3 **  And when i'm rebooting ST :

![](http://image.noelshack.com/fichiers/2015/41/1444159183-step3.jpg)

I just don't get it. I'm used to this procedure, and it actually work well with other themes on the same pc. Any idea about what's going on ?

Thanks in advance !

Edit: The console show this when i simply use itg.flat : 

```
top level value must be an array
```

There must be a problem within a conf file... I'm still looking.

**Comment by itsthatguy** [comment]
This is a great find. I'd love to see this finished, #67, for the file-type icons so that everyone can use them.
