### ISSUE TITLE
how to enable file icon?

### ISSUE THREAD

**Issue by ohblue** [itsthatguy/theme-itg-flat#82]

**Comment by roberthlima** [comment]
also I want to know

**Comment by itsthatguy** [comment]
`itg_show_file_icons: true`

**Comment by roberthlima** [comment]
itg_show_file_icons: true

## _don't work_

**Comment by ohblue** [comment]
@itsthatguy not working

**Comment by roberthlima** [comment]
open this issue, not working

**Comment by itsthatguy** [comment]
Ah, the PR never got merged. I invite new PRs.

https://github.com/itsthatguy/theme-itg-flat/pull/67
